import React from 'react'

export const Faq = () => {
  return (
    <section id='faq' className='w-5/6 mx-auto pb-12'>
      <h1 className='text-5xl font-bold text-center py-12'>FAQ</h1>
      <div className="join join-vertical w-full rounded">
        {/* Question 9.1 */}
        <div className="collapse collapse-arrow join-item border-base-300 border">
          <input type="radio" name="react-faq" defaultChecked />
          <div className="collapse-title text-xl font-medium">What is React.js and explain the concept of "components" in React.</div>
          <div className="collapse-content">
            <p>React.js is a JavaScript library for building user interfaces, especially for single-page applications. It enables developers to create reusable UI components. Components in React are independent, reusable pieces of UI that can be combined to build complex user interfaces. A component can be either a function or a class and returns React elements describing what should appear on the screen.</p>
          </div>
        </div>

        {/* Question 9.2 */}
        <div className="collapse collapse-arrow join-item border-base-300 border">
          <input type="radio" name="react-faq" />
          <div className="collapse-title text-xl font-medium">What is JSX in React, and how does it work?</div>
          <div className="collapse-content">
            <p>JSX (JavaScript XML) is a syntax extension for JavaScript used in React to describe the UI. JSX allows you to write HTML-like code inside JavaScript files, which is then transformed into regular JavaScript function calls by Babel (a transpiler). JSX makes it easier to visualize the structure of the UI and integrates seamlessly with JavaScript logic.</p>
          </div>
        </div>

        {/* Question 9.3 */}
        <div className="collapse collapse-arrow join-item border-base-300 border">
          <input type="radio" name="react-faq" />
          <div className="collapse-title text-xl font-medium">What is the Virtual DOM, and how does React use it to optimize performance?</div>
          <div className="collapse-content">
            <p>The Virtual DOM is an in-memory representation of the real DOM elements generated by React components. When the state of an object changes, React first updates the Virtual DOM. Then, it compares the Virtual DOM with the previous version using a process called "reconciliation" and efficiently updates the real DOM, applying only the changes. This optimization reduces the need for costly DOM manipulations and enhances performance.</p>
          </div>
        </div>

        {/* Question 9.4 */}
        <div className="collapse collapse-arrow join-item border-base-300 border">
          <input type="radio" name="react-faq" />
          <div className="collapse-title text-xl font-medium">Explain the concept of "props" in React and how they are used.</div>
          <div className="collapse-content">
            <p>Props (short for "properties") are inputs passed to React components from their parent components. Props are used to pass data and event handlers to child components, allowing for reusable components with customizable data. Props are immutable, meaning they cannot be modified by the receiving component and are used to render dynamic data.</p>
          </div>
        </div>

        {/* Question 9.5 */}
        <div className="collapse collapse-arrow join-item border-base-300 border">
          <input type="radio" name="react-faq" />
          <div className="collapse-title text-xl font-medium">What is "state" in React, and how does it differ from props?</div>
          <div className="collapse-content">
            <p>State is a special object in React components that stores data that can change over time and affect what is rendered on the screen. Unlike props, which are passed to the component and are immutable, state is managed within the component itself and can be updated by the component. When the state changes, the component re-renders to reflect the updated data.</p>
          </div>
        </div>

        {/* Question 9.6 */}
        <div className="collapse collapse-arrow join-item border-base-300 border">
          <input type="radio" name="react-faq" />
          <div className="collapse-title text-xl font-medium">Explain the useState hook and provide an example of how it is used.</div>
          <div className="collapse-content">
            <p>The <code>useState</code> hook is a React hook that allows functional components to have state. It returns an array with two elements: the current state value and a function to update it. Here is an example:</p>
            <pre><code>{`const [count, setCount] = useState(0);

function increment() {
  setCount(count + 1);
}

return (
  <div>
    <p>Count: {count}</p>
    <button onClick={increment}>Increment</button>
  </div>
);`}</code></pre>
          </div>
        </div>

        {/* Question 9.7 */}
        <div className="collapse collapse-arrow join-item border-base-300 border">
          <input type="radio" name="react-faq" />
          <div className="collapse-title text-xl font-medium">What is the purpose of the useEffect hook in React, and when would you use it?</div>
          <div className="collapse-content">
            <p>The <code>useEffect</code> hook is used to perform side effects in functional components, such as fetching data, subscribing to events, or manipulating the DOM. It takes a function as an argument and runs after the component renders. You can also pass dependencies to <code>useEffect</code> so it runs only when specific values change. Example use cases include data fetching or setting up timers.</p>
          </div>
        </div>
      </div>


    </section>
  )
}
